name: dart_china
description: The official mobile app of dart-china.org, built with flutter.
publish_to: 'none'
version: 1.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  discourse_api:
    git:
      url: git@github.com:jarontai/discourse_api.git
  full_screen_image:
    git:
      url: git@github.com:jarontai/full_screen_image.git
      ref: jarontai
  jpush_flutter:
    git:
      url: git@github.com:jarontai/jpush-flutter-plugin.git
      ref: jarontai
  badges: ^2.0.1
  bloc: ^7.0.0
  bugly_crash: ^0.0.6
  cached_network_image: ^3.0.0
  connectivity_plus: ^2.1.0
  cupertino_icons: ^1.0.2
  device_preview: ^1.2.0
  equatable: ^2.0.2
  extended_image: ^8.0.3
  flutter_bloc: ^7.0.0
  flutter_dotenv: ^5.0.0
  flutter_easyloading: ^3.0.0
  flutter_markdown: ^0.7.5
  flutter_zoom_drawer: ^3.2.0
  get_it: ^7.7.0
  html_editor_enhanced: ^2.2.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  logger: ^2.5.0
  package_info_plus: ^8.1.3
  path_provider: ^2.0.1
  photo_view: ^0.15.0
  reactive_forms: ^17.0.1
  result_type: ^1.0.0
  rxdart: ^0.27.1
  share_plus: ^10.1.4
  shared_preferences: ^2.0.5
  url_launcher: ^6.0.6

# dependency_overrides:
#   discourse_api:
#     path: ../../discourse_api
#   html2md:
#     path: ../../html2md    
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  flutter_launcher_icons: ^0.9.0
  flutter_lints: ^4.0.0
  injectable_generator: null
  lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/logo_dart.png
    - assets/icon/logo_dart_ios.png
    - assets/text/tos.txt
    - assets/text/privacy.txt
    - .env

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path_android: "assets/icon/logo_dart.png"
  image_path_ios: "assets/icon/logo_dart_ios.png"
